### ISSUE TITLE
<Feature Request> Preferred or default languages, and search bar in the "Target Language" option to make searches faster

### ISSUE THREAD

**Issue by Terkyz** [MahanRahmati/translate#10]
The idea of ​​the default language is so I don't have to manually change the language I want to translate to

And the search bar is to make the language selection faster

It would also be interesting to be able to choose which translation API is being used, although perhaps it is a bit unnecessary

**Comment by MahanRahmati** [comment]
> The idea of ​​the default language is so I don't have to manually change the language I want to translate to

I don't think I would add it, but a PR is always welcomed.

> And the search bar is to make the language selection faster

I will add search bar.

> It would also be interesting to be able to choose which translation API is being used, although perhaps it is a bit unnecessary

For translation APIs there is [this](https://github.com/thedaviddelta/lingva-translate/issues/109).

**Comment by MahanRahmati** [comment]
I will close this issues.
