### ISSUE TITLE
Proposal - translation of UI

### ISSUE THREAD

**Issue by Ilithy** [MahanRahmati/translate#52]
Greeting,
do you accept translation proposals? (in French for my part)?

and if yes how to deal with the strings.dart file (should it be in a folder, or name it differently?)

Thanks a lot.

**Comment by MahanRahmati** [comment]
Hello there!
For translation you need to update files inside  lib/l10n .
app_fr.arb is the file for French.

For example:
```
{
    "helloWorld": "¡Hola Mundo!"
}
```
you can read more [here](https://docs.flutter.dev/development/accessibility-and-localization/internationalization).

**Comment by Ilithy** [comment]
Hi;
Thank you for preparing the work, the docs and the example for me, it's quite telling, so I hope I haven't made a mistake.
