### ISSUE TITLE
Custom Lingva instance

### ISSUE THREAD

**Issue by hajdulak** [MahanRahmati/translate#71]
Hello,

I run a private Lingva instance and would like to use it with this app. Is is possible to add that feature? I know I could probably edit the source and build the app myself, but having an option to type in a link and press OK would be extra lovely for all of us self-hosting folks.

**Comment by Ilithy** [comment]
Hi,
@hajdulak in case it is useful for you, the android application [Translate You](https://github.com/Bnyro/TranslateYou) has this functionality.
